services:
  mariadb:
    image: mariadb:11.4
    container_name: mariadb-dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: board
      MYSQL_USER: hy
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
  # spring-boot:

volumes:
  mariadb_data:
